### ISSUE TITLE
Solving a heat equation on a surface failed.

### ISSUE THREAD

**Issue by YuCrazing** [gismo/gismo#283] opened 2019-01-14 12:12 UTC
I make a patch R^2 -> R^3, to solve the heat equation on a surface, but get a runtime error. So, how to solve a heat equation on a surface?

**Comment by dominik-mokris-mtu** [comment] 2019-09-03 16:47
The cause is difficult to guess at. Can you share a MWE (minimal working example) so that we can see what exactly you do?

**Comment by hverhelst** [comment] 2022-12-12 13:38
@YuCrazing is this still relevant? Otherwise we close the issue.

**Closed** 2022-12-14 08:34 UTC
